<a href="https://colab.research.google.com/github/forhigh/numerical_geotech_graduate/blob/main/Mat_algebra_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction to Numpy Arrays

### Importing Numpy

In [ ]:
import numpy as np

### Creating an array

In [ ]:
l = [1.0, 2.0, 3.0]
a = np.array(l)

### Displaying array

In [ ]:
print(f"a: {a}")

a: [1. 2. 3.]


### Functions to Create Arrays
### Empty:

In [ ]:
b = np.empty([3, 3])
print(f"b: \n{b}")

b: 
[[1.63527666e-316 0.00000000e+000 7.90505033e-323]
 [1.65310887e-316 0.00000000e+000 0.00000000e+000]
 [9.88131292e-324 0.00000000e+000 3.95252517e-322]]


### Zeros:

In [ ]:
c = np.zeros([3, 5])
print(f"c: \n{c}")

c: 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Ones:

In [ ]:
d = np.ones([5])
print(f"d: {d}")

d: [1. 1. 1. 1. 1.]


### Combining Arrays
### Vertical Stack:

In [ ]:
a1 = np.array([1, 2, 3])
print(f"a1: {a1}\n")

a2 = np.array([4, 5, 6])
print(f"a2: {a2}")

a1: [1 2 3]

a2: [4 5 6]


In [ ]:
a3 = np.vstack((a1, a2))
print(f"a3: \n{a3}\n")

print(f"a3.shape: {a3.shape}")

a3: 
[[1 2 3]
 [4 5 6]]

a3.shape: (2, 3)


### Horizontal Stack:

In [ ]:
a4 = np.array([1, 2, 3])
print(f"a4: {a4}\n")

a5 = np.array([4, 5, 6])
print(f"a4: {a4}\n")


# create horizontal stack
a6 = np.hstack((a4, a5))
print(f"a6: {a6}\n")

print(f"a6.shape: {a6.shape}")


a4: [1 2 3]

a4: [1 2 3]

a6: [1 2 3 4 5 6]

a6.shape: (6,)
