<a href="https://colab.research.google.com/github/forhigh/numerical_geotech_graduate/blob/main/Mat_algebra_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Eigen Decomposition
### Calculation of Eigendecomposition:
    An eigendecomposition is calculated on a square matrix using an efficient
    iterative algorithm, of which we will not go into the details. Often an 
    eigenvalue is found first, then an eigenvector is found to solve the 
    equation as a set of coefficients.

In [ ]:
from numpy import array
from numpy.linalg import eig

# define a square matrix
A = array([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]])
print(f"A: \n{A}\n")

#factorize
values, vectors = eig(A)
print(f"values: {values}\n")
print(f"vectors: \n{vectors}")

A: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

values: [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]

vectors: 
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


### Confirm an Eigenvalue and Eigenvector:
    The eigenvectors are returned as a matrix with the same dimensions as the 
    parent matrix, where each column is an eigenvector, e.g. the first 
    eigenvector is vectors[:, 0]. Eigenvalues are returned as a list, where
    value indices in the returned array are paired with eigenvectors by 
    column index, e.g. the first eigenvalue at values[0] is paired with the 
    first eigenvector at vectors[:, 0].

In [ ]:
from numpy import array
from numpy.linalg import eig

A = array([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]])
print(f"A: \n{A}\n")

# factorize
values, vectors = eig(A)

# confirm first eigenvector
B = A.dot(vectors[:, 0])
print(f"B: {B}\n")

C = vectors[:, 0] * values[0]
print(f"C: {C}")

A: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

B: [ -3.73863537  -8.46653421 -13.19443305]

C: [ -3.73863537  -8.46653421 -13.19443305]


### Reconstruct Matrix:
    We can reverse the process and reconstruct the original matrix given 
    only the eigenvectors and eigenvalues. First, the list of eigenvectors
    must be taken together as a matrix, where each vector becomes a row. 
    The eigenvalues need to be arranged into a diagonal matrix. The NumPy 
    diag() function can be used for this. Next, we need to calculate the 
    inverse of the eigenvector matrix, which we can achieve with the inv() 
    NumPy function. Finally, these elements need to be multiplied together 
    with the dot() function.

In [ ]:
# reconstruct matrix
from numpy import diag, array
from numpy.linalg import inv, eig

# define matrix
A = array([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]])
print(f"A: \n{A}\n")

# factorize
values, vectors = eig(A)

# create matrix from eigenvectors
Q = vectors

# create inverse of eigenvectors matrix
R = inv(Q)

# create diagonal matrix from eigenvalues
L = diag(values)

# reconstruct the original matrix
B = Q.dot(L).dot(R)
print(f"B: \n{B}")

A: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

B: 
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### Example for Principle Stresses:
A stress state in 3D space is defined. The principle stresses and corresponding unit normals are evaluated.

In [ ]:
# define a 3D stress state
sig = array([[2, 1, 1],
           [1, 3, 1],
           [1, 1, 1]])
print(f"sig = \n{sig}\n")

#factorize
lambda_val, n_vectors = eig(sig)
print(f"lambda_val = {lambda_val}\n")
print(f"n_vectors = \n{n_vectors}")

sig = 
[[2 1 1]
 [1 3 1]
 [1 1 1]]

lambda_val = [4.21431974 1.46081113 0.32486913]

n_vectors = 
[[-0.52065737 -0.73923874 -0.42713229]
 [-0.75578934  0.63178128 -0.17214786]
 [-0.39711255 -0.23319198  0.88765034]]


Reconstruct principle stresses.

In [ ]:
re_sig=(n_vectors.T).dot(sig).dot(n_vectors)
print(f"re_sig = \n{re_sig}")

re_sig = 
[[ 4.21431974e+00  8.18472522e-16 -1.33016898e-16]
 [ 6.78974907e-16  1.46081113e+00  5.04206567e-16]
 [-2.14488225e-16  4.61728511e-16  3.24869129e-01]]
